apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: %APP_NAME%
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: %APP_NAME%
    spec:
      containers:
      - name: curri-elm
        image: %REGISTRY%/%APP_NAME%:%VERSION%
        resources:
          requests:
            cpu: 400m
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
