apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: curri-elm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: curri-elm
    spec:
      containers:
      - name: curri-elm
        image: registry.gitlab.com/kolov/curri-elm:master
        resources:
          requests:
            cpu: 400m
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
